import {
  HomeIcon,
  BuildingOffice2Icon,
  TagIcon,
  SparklesIcon,
  TruckIcon,
  ArchiveBoxIcon,
  UsersIcon,
  UserGroupIcon,
  ShoppingCartIcon,
  BanknotesIcon,
  ClipboardDocumentCheckIcon,
  ChartBarSquareIcon,
  Cog6ToothIcon,
  CalendarDaysIcon,
  WrenchScrewdriverIcon,
  GlobeAltIcon,
  Squares2X2Icon,
  FireIcon,
  CalculatorIcon,
  InboxArrowDownIcon,
  GiftIcon,
  DocumentTextIcon,
  ArrowUturnLeftIcon,
  CreditCardIcon,
  ReceiptPercentIcon,
  BeakerIcon,
} from '@heroicons/react/24/outline';

export const NAVIGATION = [
  {
    section: 'General',
    items: [
      {
        name: 'Inicio',
        href: '/dashboard',
        icon: HomeIcon,
        roles: [
          'SUPER_ADMIN',
          'ADMIN',
          'RECEPCIONISTA',
          'COORDINADOR',
          'AUXILIAR',
          'ASESOR',
          'BODEGUERO',
          'VENTAS',
          'CAJA',
          'MESERO',
          'COCINERO',
          'PROFESIONAL',
          'BARBERO',
        ],
      },
      {
        name: 'Locales',
        href: '/dashboard/locals',
        icon: BuildingOffice2Icon,
        roles: ['SUPER_ADMIN'],
      },
    ],
  },

  {
    section: 'Inventario',
    items: [
      {
        name: 'Categorías',
        href: '/dashboard/categories',
        icon: TagIcon,
        roles: ['SUPER_ADMIN', 'ADMIN', 'ASESOR', 'RECEPCIONISTA', 'BODEGUERO'],
      },
      {
        name: 'Marcas',
        href: '/dashboard/brands',
        icon: SparklesIcon,
        roles: ['SUPER_ADMIN', 'ADMIN', 'ASESOR', 'RECEPCIONISTA', 'BODEGUERO'],
      },
      {
        name: 'Proveedores',
        href: '/dashboard/providers',
        icon: TruckIcon,
        roles: ['SUPER_ADMIN', 'ADMIN', 'ASESOR', 'RECEPCIONISTA', 'BODEGUERO'],
      },
      {
        name: 'Inventario',
        href: '/dashboard/inventory',
        icon: ArchiveBoxIcon,
        roles: [
          'SUPER_ADMIN',
          'ADMIN',
          'ASESOR',
          'RECEPCIONISTA',
          'BODEGUERO',
          'VENTAS',
        ],
      },
      {
        name: 'Insumos',
        href: '/dashboard/supplies',
        icon: BeakerIcon,
        roles: [
          'SUPER_ADMIN',
          'ADMIN',
          'RECEPCIONISTA',
          'CAJA',
          'COCINERO',
        ],
      },
      {
        name: 'Compras',
        href: '/dashboard/purchases',
        icon: InboxArrowDownIcon,
        roles: [
          'SUPER_ADMIN',
          'ADMIN',
          'ASESOR',
          'RECEPCIONISTA',
          'BODEGUERO',
        ],
      },
    ],
  },

  {
    section: 'Ventas',
    items: [
      {
        name: 'Realizar Factura',
        href: '/dashboard/sales',
        icon: BanknotesIcon,
        roles: [
          'SUPER_ADMIN',
          'ADMIN',
          'ASESOR',
          'RECEPCIONISTA',
          'VENTAS',
          'CAJA',
        ],
      },
      {
        name: 'Mesas',
        href: '/dashboard/mesas',
        icon: Squares2X2Icon,
        roles: [
          'SUPER_ADMIN',
          'ADMIN',
          'ASESOR',
          'RECEPCIONISTA',
          'CAJA',
          'MESERO',
        ],
      },
      {
        name: 'Cocina',
        href: '/dashboard/kitchen',
        icon: FireIcon,
        roles: [
          'SUPER_ADMIN',
          'ADMIN',
          'ASESOR',
          'RECEPCIONISTA',
          'AUXILIAR',
          'MESERO',
          'COCINERO',
        ],
      },
      {
        name: 'Pedidos',
        href: '/dashboard/orders',
        icon: ShoppingCartIcon,
        roles: [
          'SUPER_ADMIN',
          'ADMIN',
          'ASESOR',
          'RECEPCIONISTA',
          'VENTAS',
          'CAJA',
        ],
      },
      {
        name: 'Ventas Realizadas',
        href: '/dashboard/delivered_sales',
        icon: ClipboardDocumentCheckIcon,
        roles: [
          'SUPER_ADMIN',
          'ADMIN',
          'ASESOR',
          'RECEPCIONISTA',
          'CAJA',
          'VENTAS',
        ],
      },
      {
        name: 'Devoluciones',
        href: '/dashboard/returns',
        icon: ArrowUturnLeftIcon,
        roles: ['SUPER_ADMIN', 'ADMIN', 'ASESOR', 'RECEPCIONISTA'],
      },
      {
        name: 'Cartera',
        href: '/dashboard/cartera',
        icon: CreditCardIcon,
        roles: ['SUPER_ADMIN', 'ADMIN', 'ASESOR', 'RECEPCIONISTA', 'CAJA'],
      },
      {
        name: 'Caja',
        href: '/dashboard/cash',
        icon: CalculatorIcon,
        roles: [
          'SUPER_ADMIN',
          'ADMIN',
          'ASESOR',
          'RECEPCIONISTA',
          'CAJA',
          'VENTAS',
        ],
      },
      {
        name: 'Consignaciones',
        href: '/dashboard/bank',
        icon: BanknotesIcon,
        // Cualquier rol del negocio puede ver las consignaciones.
        roles: [
          'SUPER_ADMIN',
          'COORDINADOR',
          'ADMIN',
          'ASESOR',
          'AUXILIAR',
          'BODEGUERO',
          'VENTAS',
          'BARBERO',
          'CAJA',
          'RECEPCIONISTA',
          'MESERO',
          'COCINERO',
          'PROFESIONAL',
        ],
      },
      {
        name: 'Cotizaciones',
        href: '/dashboard/quotes',
        icon: DocumentTextIcon,
        roles: [
          'SUPER_ADMIN',
          'ADMIN',
          'ASESOR',
          'RECEPCIONISTA',
          'VENTAS',
        ],
      },
    ],
  },

  {
    section: 'Clientes',
    items: [
      {
        name: 'Clientes',
        href: '/dashboard/customers',
        icon: UsersIcon,
        roles: [
          'SUPER_ADMIN',
          'ADMIN',
          'ASESOR',
          'RECEPCIONISTA',
          'VENTAS',
          'CAJA',
        ],
      },
      {
        name: 'Fidelización',
        href: '/dashboard/loyalty',
        icon: GiftIcon,
        roles: ['SUPER_ADMIN', 'ADMIN', 'ASESOR', 'RECEPCIONISTA'],
      },
    ],
  },

  {
    section: 'Operación',
    items: [
      {
        name: 'Citas',
        href: '/dashboard/appointments',
        icon: CalendarDaysIcon,
        roles: [
          'SUPER_ADMIN',
          'ADMIN',
          'BARBERO',
          'PROFESIONAL',
          'RECEPCIONISTA',
        ],
      },
      {
        name: 'Servicios',
        href: '/dashboard/services',
        icon: WrenchScrewdriverIcon,
        roles: ['SUPER_ADMIN', 'ADMIN', 'RECEPCIONISTA'],
      },
      {
        name: 'Gastos',
        href: '/dashboard/expenses',
        icon: ChartBarSquareIcon,
        roles: ['SUPER_ADMIN', 'ADMIN', 'ASESOR', 'RECEPCIONISTA'],
      },
      {
        name: 'Estadísticas',
        href: '/dashboard/statistics',
        icon: ChartBarSquareIcon,
        roles: ['SUPER_ADMIN'],
      },
      {
        name: 'Impuestos (IVA)',
        href: '/dashboard/impuestos',
        icon: ReceiptPercentIcon,
        roles: ['SUPER_ADMIN', 'ADMIN'],
      },
    ],
  },

  {
    section: 'Administración',
    items: [
      {
        name: 'Usuarios / Roles',
        href: '/dashboard/users',
        icon: UserGroupIcon,
        roles: ['SUPER_ADMIN'],
      },
      {
        name: 'Tienda online',
        href: '/dashboard/website',
        icon: GlobeAltIcon,
        roles: ['SUPER_ADMIN'],
      },
      {
        name: 'Configuración',
        href: '/dashboard/settings',
        icon: Cog6ToothIcon,
        roles: ['SUPER_ADMIN', 'ADMIN'],
      },
    ],
  },
];
