export const getEmptySale = () => ({
  items: [],
  paymentMethod: '',
  localId: '',
  userId: '',
  customerId: '',
  totalAmount: '',
  paymentStatus: 'PAGADA',
  saleDate: '',
  discount: '',
  notes: '',
});

export const getFormFieldsSales = (t = {}) => [
  {
    name: 'items',
    label: 'Productos o servicios',
    type: 'productSelect',
    required: true,
    source: 'products',
    disabled: false,
  },
  {
    name: 'paymentMethod',
    label: 'Método de Pago',
    type: 'select',
    required: true,
    source: 'paymentMethod',
    disabled: false,
  },
  {
    name: 'localId',
    label: 'Local / Punto de Venta',
    type: 'select',
    required: true,
    source: 'locals',
    disabled: false,
  },
  {
    name: 'userId',
    label: 'Atendido por',
    type: 'select',
    required: true,
    source: 'users',
    disabled: false,
  },
  {
    name: 'paymentStatus',
    label: 'Estado',
    type: 'select',
    required: true,
    options: [
      { id: 'PAGADA', name: 'PAGADA' },
      { id: 'FIADO', name: 'FIADO' },
    ],
    source: 'paymentStatus',
    disabled: false,
  },
  {
    name: 'saleDate',
    label: 'Fecha de la Venta',
    type: 'datetime-local',
    required: true,
    source: null,
    disabled: false,
  },
  {
    name: 'customerId',
    label: `${t.customer || 'Cliente'} (opcional)`,
    type: 'searchSelect',
    required: false,
    source: 'customers',
    disabled: false,
    hint: 'Déjalo vacío para venta de mostrador (Consumidor Final).',
  },
  {
    name: 'notes',
    label: 'Observaciones',
    type: 'textarea',
    required: false,
    source: null,
    disabled: false,
  },
];
